10/06/2024 14:35:53;Início da Preparação;Notificação
10/06/2024 14:35:53;Parâmetro de Execução Gestor 2;Alerta
10/06/2024 14:35:53;Apagando arquivos do envio anterior;Notificação
10/06/2024 14:35:53;Arquivos do dia anterior excluídos;Notificação
10/06/2024 14:35:53;Abrindo conexão com o banco de dados;Notificação
10/06/2024 14:35:53;Abrindo conexão com o banco de dados;Notificação
10/06/2024 14:35:53;Conexão com o banco de dados realizada;Notificação
10/06/2024 14:35:53;Periodo Inicial:16/05/24;Notificação
10/06/2024 14:35:53;Periodo Final:08/06/24;Notificação
10/06/2024 14:35:54;Query: SELECT * FROM RM.PLN_OCOR_HEXTRAS where data between to_date('16/05/24', 'dd/mm/yy') and to_date('08/06/24', 'dd/mm/yy')and codfilial in (43, 94, 97) and (codequipe is null or codequipe = '009') Registros: 272;Notificação
10/06/2024 14:35:54;Término Obter Dados: 10/06/2024 14:35:54;Notificação
10/06/2024 14:35:54;Início Formatar Excel: 10/06/2024 14:35:54;Notificação
10/06/2024 14:35:54;Formatando a planilha: Administração RH 10/06/2024 14:35:54;Notificação
10/06/2024 14:35:55;Gravando lista de e-Mails;Notificação
10/06/2024 14:35:55;Concluindo lista de e-Mails;Notificação
10/06/2024 14:35:55;Término Formatar Excel: 10/06/2024 14:35:55;Notificação
10/06/2024 14:35:55;Enviando e-mails aos usuários;Alerta
10/06/2024 14:35:55;Preparando o e-mail;Notificação
10/06/2024 14:35:55;!!!!!!!!!!!!!!!!!! Ocorreu um erro : EXCEPTION IN (C:\RHExcel\geraexcel.py, LINE 929 "fnEnviaEmails(iTipo, sDestinatario,wbNome, ExcelFileName, logFile )"): [Errno 2] No such file or directory: '2024_06_09_Apuração de Ponto.xlsx';Erro
10/06/2024 14:35:55;Acabou ********************************;Notificação
